=== wsyski/ehub-boot/local/src/main/xsd/se/elib/library/GetProduct.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="getproduct"
           targetNamespace="https://www.elib.se/webservices/schema/getproduct.xsd"
           attributeFormDefault="unqualified" elementFormDefault="unqualified"
           xmlns="https://www.elib.se/webservices/schema/getproduct.xsd"
           xmlns:mstns="https://www.elib.se/webservices/schema/getproduct.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="en">
            Get a product item schema.
            Copyright 2010 Elib AB. All rights reserved.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="code" type="xs:unsignedByte"/>
                            <xs:element name="message" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="created_date" type="xs:date"/>
                                        <xs:element name="updated_date" type="xs:date"/>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="status">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:unsignedByte"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="language">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="lang" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="coverimage" type="xs:string"/>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="teaser">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" maxOccurs="unbounded" name="link"/>
                                                    <xs:element minOccurs="0" maxOccurs="unbounded" name="text"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="external_ids">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded" name="external_id">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="id_type" type="xs:string"/>
                                                                <xs:element name="id" type="xs:unsignedLong"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="contributors">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" maxOccurs="unbounded" name="contributor">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="type" type="xs:string"/>
                                                                <xs:element name="first_name" type="xs:string"/>
                                                                <xs:element name="family_name" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="formats">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" maxOccurs="unbounded" name="format">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="format_id" type="xs:unsignedInt"/>
                                                                <xs:element name="name" type="xs:string"/>
                                                                <xs:element name="description" type="xs:string"/>
                                                                <xs:element name="icon" type="xs:string"/>
                                                                <xs:element name="size_bytes" type="xs:unsignedInt"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="price">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="currency" type="xs:string"/>
                                                    <xs:element name="amount" type="xs:unsignedInt"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="publisher">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="external_id" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="first_published" type="xs:date"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="categories">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" maxOccurs="unbounded" name="category">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" type="xs:string" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wsyski/ehub-boot/local/src/test/xml/se/elib/library/GetProduct.xml
<?xml version="1.0" encoding="utf-8"?>
<xs1:response xmlns:xs1="https://www.elib.se/webservices/schema/getproduct.xsd"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.elib.se/webservices/schema/getproduct.xsd ../../../../main/xsd/se/elib/GetProduct.xsd">
  <status>
    <code>101</code>
    <message>Info - Ok</message>
  </status>
  <data>
    <product>
      <created_date>2011-10-20</created_date>
      <updated_date>2012-05-30</updated_date>
      <title>Steve Jobs : En biografi</title>
      <status>
        <id>9</id>
        <description>Aktiv</description>
      </status>
      <language lang="iso 639-1">sv</language>
      <coverimage>http://www.elib.se/cover_images/9100128260.jpg</coverimage>
      <teaser />
      <external_ids>
        <external_id>
          <id_type>ISBN</id_type>
          <id>9100128260</id>
        </external_id>
        <external_id>
          <id_type>ISBN13</id_type>
          <id>9789100128265</id>
        </external_id>
      </external_ids>
      <contributors>
        <contributor>
          <type>författare</type>
          <first_name>Walter</first_name>
          <family_name>Isaacson</family_name>
        </contributor>
        <contributor>
          <type>översättare</type>
          <first_name>Thomas</first_name>
          <family_name>Engström</family_name>
        </contributor>
        <contributor>
          <type>översättare</type>
          <first_name>Roland</first_name>
          <family_name>Poirier Martinsson</family_name>
        </contributor>
      </contributors>
      <formats>
        <format>
          <format_id>58</format_id>
          <name>Epub with Adobe DRM for PC, Mac and e-book readers</name>
          <size_bytes>3419309</size_bytes>
        </format>
      </formats>
      <price>
        <currency>SEK</currency>
        <amount>2000</amount>
      </price>
      <publisher>
        <name>Albert Bonniers förlag</name>
        <external_id>8400</external_id>
      </publisher>
      <first_published>2011-10-24</first_published>
      <description>&lt;p&gt;Steve Jobs, i-konen&lt;/p&gt;
&lt;p&gt;Den egensinnige kreatören, den maniske perfektionisten. Vi kände honom som den store uppfinnaren, den som revolutionerat vårt sätt att umgås och förhålla oss till världen och totalt förändrat vårt vardagsliv. Men vem var han? Och hur kom han att bli till den ikon han är idag? Vilka var hans drivkrafter? Vilka tankar och människor påverkade honom, stöttade honom, bjöd honom motstånd?&lt;/p&gt;
&lt;p&gt;För första gången berättar Steve Jobs om sitt liv och sitt arbete. Under flera års tid och i över fyrtio intervjuer har Steve Jobs berättat öppenhjärtigt för vetenskapshistorikern Walter Isaacson om sin uppväxt, sitt privatliv och sin karriär. Han har inga skäl kvar att dölja någonting. Här berättar han allt.&lt;/p&gt;
&lt;p&gt;Det här är historien om en man som mer än någon annan personifierar vår tid, en symbol för den mänskliga kreativiteten och ett synsätt där form och innehåll är lika viktiga.&lt;/p&gt;
&lt;p&gt;Steve Jobs har, med sitt driv och sin ständiga jakt på perfektion, totalt revolutionerat vår värld och vårt sätt att leva. Han släppte in datorn i hemmet, gav den tecknade filmen en renässans, stöpte i ett enda slag om musikindustrin med sin i-Pod och med i-Phonen förvandlade han telefonen till ett oumbärligt vardagsredskap -- och en väldigt kul leksak. Samtidigt.&lt;/p&gt;
&lt;p&gt;Steve Jobs avled i oktober 2011, 56 år gammal.&lt;/p&gt;
&lt;p&gt;&lt;/p&gt;</description>
      <categories>
        <category type="BIC_code">K</category>
        <category type="Elib_Category">302</category>
      </categories>
    </product>
  </data>
</xs1:response>
